### ISSUE TITLE
Opa check seems to run only against stages rego files

### ISSUE THREAD

**Issue by ryuheechul** [anderseknert/pre-commit-opa#3]
**Describe the bug**

`opa-check` fails with pre commit hook however, running `opa check .` manually works.

**My situation**
- `a.rego` is already committed.
- `b.rego` is staged and it imports `a.rego`
- `opa-check` fails when I try to commit

**My speculation**
I'm relatively new to pre-commit however I have a feeling that `opa check` via `opa-check` is running only against the staged files, which means `opa check b.rego` and it will fail because it doesn't include `a.rego` which is necessary. 

Either `opa check a.rego b.rego` or `opa check *.rego` or `opa check .` should succeed

**Comment by anderseknert** [comment]
Thanks for reporting this @ryuheechul! 👍 Had previously changed other commands to include all Rego files but somehow forgotten to do so for OPA check. Fixed via https://github.com/anderseknert/pre-commit-opa/commit/55996435e375873481c0fea124eb6c98531a38a5, and I'll push a new release in a few minutes.

**Comment by anderseknert** [comment]
@ryuheechul https://github.com/anderseknert/pre-commit-opa/releases/tag/v1.4.1

**Comment by ryuheechul** [comment]
@anderseknert cool and thanks!
